name = "yum"
version = "1.0.0"
description = "A YAML parser, resolver, decoder bridge, and emitter for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "matiascr", repo = "yum" }
links = [
  { title = "YAML 1.2 specification", href = "https://yaml.org/spec/1.2.2/" },
]

internal_modules = [
  "yum/yaml/lexer",
  "yum/yaml/lexer/*",
  "yum/yaml/parser",
  "yum/yaml/parser/*",
  "yum/yaml/document",
  "yum/yaml/dynamic",
  "yum/yaml/emitter",
  "yum/yaml/resolver",
  "yum/yaml/token",
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
nibble = ">= 1.1.4 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.1 and < 3.0.0"
