name = "yum"
version = "1.0.0"
internal_modules = [
  "yum/yaml/lexer",
  "yum/yaml/lexer/*",
  "yum/yaml/parser",
  "yum/yaml/parser/*",
  "yum/yaml/token",
]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
nibble = { git = "git@github.com:matiascr/nibble.git", ref = "main" }
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.1 and < 3.0.0"
